 steps:
 #step 0 pull prev image for caching
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     docker pull gcr.io/$PROJECT_ID/rmthks:latest || exit 0
 #step1 build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [
     'build', 
     '-t', 'gcr.io/$PROJECT_ID/rmthks:latest', 
     '--cache-from', 'gcr.io/$PROJECT_ID/rmthks:latest',
     '.']
 #step2 push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/rmthks:latest']
 #step3 Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'rmthks'
   - '--image'
   - 'gcr.io/$PROJECT_ID/rmthks:latest'
   - '--region'
   - 'us-central1'
   - '--allow-unauthenticated'
   - '--platform'
   - 'managed'
 images:
 - 'gcr.io/$PROJECT_ID/rmthks:latest'